name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Ensure this workflow waits for check workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wait-for-check:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for check workflow
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          check-name: 'Type Check & Lint'
          allowed-conclusions: success

  cypress-run:
    needs: wait-for-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.14.2

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.STORE_PATH }}
            ~/.cache/Cypress
          key: ${{ runner.os }}-pnpm-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-cypress-

      - name: Install dependencies
        run: pnpm install

      - name: Install Cypress binary
        run: pnpm exec cypress install

      - name: Run Coverage Tests
        env:
          NODE_ENV: test
          NEXT_PUBLIC_IS_TEST: 'true'
          NEXT_PUBLIC_BLOB_READ_WRITE_TOKEN: 'vercel_blob_test_token'
        run: pnpm coverage

      - name: Upload Coverage Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: cypress/results/
